name: Source Code Check

on:
    - push

jobs:
    tsc:
        name: Run Type Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"
            - run: npm i
            - run: npm run typecheck
